
version: 0.2

env:
  variables:
    IMAGE_NAME: "my-app-image"               # Name of your Docker image
    IMAGE_TAG: "latest"                      # Tag for the Docker image
    REPOSITORY_URI: 355355693719.dkr.ecr.us-east-1.amazonaws.com/docker-repo  # Replace with your ECR repository URI

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 355355693719.dkr.ecr.us-east-1.amazonaws.com
      - echo "Retrieving latest code..."
      - git pull
      - echo "Setting image tag as ${IMAGE_TAG} for build"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Docker image pushed successfully"

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - '/root/.cache/pip/**/*'
